### ISSUE TITLE
Galaxy luminosity to DUET bands

### ISSUE THREAD

**Issue by bwgref** [duet-mission/duet-astro#24]
Right now this is hard coded in "sim_galaxy" in image_utils.py. I don't know what the units of "Amplitude" are, but we should figure out how we want to scale this for the DUET bands and/or with distance?

**Comment by mheida** [comment]
I'm implementing this in my notebook now as starting with a surface brightness in ABmag/arcsec^2, convert that with duet_abmag_to_fluence to a fluence per arcsec^2, multiply by the pixel_init^2 and then applying trans_eff and eff_area to get to the 'amplitude' that is now hardcoded in sim_galaxy. Those steps could just go into the sim_galaxy code and then you can just input a surface brightness in DUET magnitudes.

**Comment by bwgref** [comment]
Closed a while ago.
