### ISSUE TITLE
Need to apply pointing jitter to construct_image

### ISSUE THREAD

**Issue by bwgref** [duet-mission/duet-astro#25]
...right now just doing the multi-PSF convolution. Will need to interface with Kristin on putting the correct numbers into the Telescope class.

**Comment by mheida** [comment]
Computation-time-wise, doing the one convolution we're doing now (with the instrument psf) takes 30 ms, and doing two convolutions (adding the jitter as a simple Gaussian2DKernel) takes 40 ms. So I've added that to the construct_image function.

**Comment by bwgref** [comment]
Closed, since we're now doing this in the PSF model itself.
