### ISSUE TITLE
Count rates in photons/s or just /s?

### ISSUE THREAD

**Issue by mheida** [duet-mission/duet-astro#29]
We should probably decide on the units for the fluences, because right now the bb_abmag_fluence and background_pixel_rate output numbers as 1/s while the general duet_abmag_to_fluence gives ph/s. 
construct_image currently wants the source and background rates in 1/s and the galaxy amplitude as a unitless value. And there may be more inconsistencies in other places as well.

**Comment by bwgref** [comment]
Good point. My vote would be to get rid of the "ph" in the ph/s in duet_abmag_to_fluence to avoid having nuisance units floating around.

**Comment by mheida** [comment]
Actually, having the photons there might be nice because then we can easily make images in photons instead of having no units.

**Comment by matteobachetti** [comment]
I'm hitting this issue now with the light curve conversion. I can make the consistent change if needed
