### ISSUE TITLE
Indexing futurewarning in diff_image.py

### ISSUE THREAD

**Issue by mheida** [duet-mission/duet-astro#36]
Diff_image is now throwing a bunch of future warnings that should probably get fixed at some point:

/Users/mheida/scripts/git/duet-astro/astroduet/diff_image.py:50: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  P_N[idx] = P_N_small
/Users/mheida/scripts/git/duet-astro/astroduet/diff_image.py:51: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  P_R[idx] = P_R_small
/Users/mheida/scripts/git/duet-astro/astroduet/diff_image.py:82: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  P_D = P_D[idx]

**Comment by matteobachetti** [comment]
On line 50, `idx` is defined as  a list.
```
    idx = [slice(N.shape[0]//2 - P_N_small.shape[0]//2,
                 N.shape[0]//2 + P_N_small.shape[0]//2 + 1),
           slice(N.shape[1]//2 - P_N_small.shape[1]//2,
                 N.shape[1]//2 + P_N_small.shape[1]//2 + 1)]
```
change it to
```
    idx = (slice(N.shape[0]//2 - P_N_small.shape[0]//2,
                 N.shape[0]//2 + P_N_small.shape[0]//2 + 1),
           slice(N.shape[1]//2 - P_N_small.shape[1]//2,
                 N.shape[1]//2 + P_N_small.shape[1]//2 + 1))
```
Similarly in the other source lines

**Comment by mheida** [comment]
Thanks! I'll fix that then.

**Comment by bwgref** [comment]
Closed?
