### ISSUE TITLE
Fix psf_size and pointing jitter

### ISSUE THREAD

**Issue by mheida** [duet-mission/duet-astro#87]
Right now:
psf_size combines the instrument psf fwhm and the jitter interpreted as fwhm
In the image construction code, jitter is interpreted as sigma. 
Config needs to be cleaned up to make this consistent.

**Comment by bwgref** [comment]
Decided that the path forward is to basically adjust Telescope().calc_radial_profile() to apply the jitter_rms convolution on top of the standard psf_model convolution (the easiest way to do this here may be to just use construct_image with dark current, read noise, and background turned off) and then  compute the FWHM based on the resulting data.

**Comment by bwgref** [comment]
This is in place now, but the wrapped "jitter_rms" numbers that are in config.py from #89 are from an Excel table from Roger. I realized after the fact that they also include the "as designed" optical PSFs, so we're essentially double-counting those. I'll go back and try to fix this on Monday,

**Comment by bwgref** [comment]
Addressed in gory detail in #93 See that PR's notes.
